apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-app
spec:
  replicas: 2  # 2 Pods pour commencer (scalabilité de base)
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: <TON_REGISTRY>/flask-app:latest  # Remplacer <TON_REGISTRY> par ton vrai Azure Container Registry (ACR)
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: flask-config
        - secretRef:
            name: flask-secrets  # Ajout du Secret pour les variables sensibles