apiVersion: apps/v1
kind: Deployment
metadata:
  name: diffus-api-deployment
  labels:
    app: flask-app
spec:
  replicas: 2  # 2 Pods pour commencer (scalabilité de base)
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: flaskapi.azurecr.io/diffus_api:latest  # L'image de ton ACR
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: flask-config
        - secretRef:
            name: flask-secrets  # Ajout du Secret pour les variables sensibles
      imagePullSecrets:
      - name: acr-auth  # Utilisation du secret acr-auth pour l'authentification
