apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
type: Opaque
data:
  AZURE_CONNECTION_STRING: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPWVsdmllO0FjY291bnRLZXk9dXBMV0lFSFRUOXRCbVBkYm1lT2U2eTk2bWgzdURZSVBaM2YrR1pNZ2lORjAxanVETWUxQy85bE5FRUFzd29iT0JVM2xxN0JxMWkvQStBU3RlbmxHcXc9PTtFbmRwb2ludFN1ZmZpeD1jb3JlLndpbmRvd3MubmV0
