name: Build and Deploy Flask App to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry (ACR)
      run: |
        echo ${{ secrets.AZURE_ACR_PASSWORD }} | docker login flaskapi.azurecr.io --username ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin

    - name: Build and Push Docker image
      run: |
        docker build -t flaskapi.azurecr.io/diffus_api:latest .
        docker push flaskapi.azurecr.io/diffus_api:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1

    - name: Deploy to AKS
      run: |
        az aks get-credentials --resource-group flaskApi_group --name diffus_app_flask
        kubectl apply -k ./k8s/
